(() => {
  const site = window.DWGC2E_SITE || {};
  const api = String(site.apiBaseUrl || '').replace(/\/$/, '');
  const key = 'dwgc2e.session';
  const $ = s => document.querySelector(s);
  const authPanel = $('#authPanel'), accountPanel = $('#accountPanel'), form = $('#accountForm');
  if (!form || !api) return;
  let mode = 'login';
  const message = (text, error = false) => { const el = $('#formMessage'); el.textContent = text || ''; el.className = `form-message${error ? ' error' : ''}`; };
  const setMode = next => { mode = next; document.querySelectorAll('[data-auth-mode]').forEach(b => b.classList.toggle('active', b.dataset.authMode === mode)); document.querySelectorAll('.register-only').forEach(el => { el.hidden = mode !== 'register'; }); $('#authSubmit').textContent = mode === 'login' ? '登录' : '创建账号'; message(''); };
  document.querySelectorAll('[data-auth-mode]').forEach(b => b.addEventListener('click', () => setMode(b.dataset.authMode))); setMode('login');
  const request = async (path, options = {}) => { const response = await fetch(`${api}${path}`, { ...options, headers: { 'content-type': 'application/json', ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || data.error_code || `请求失败（${response.status}）`); return data; };
  const loadDashboard = async token => { const headers = { Authorization: `Bearer ${token}` }; const [profile, subscription, usage, devices] = await Promise.all([request('/v1/profile', { headers }), request('/v1/subscription', { headers }), request('/v1/usage', { headers }), request('/v1/devices/bind', { method: 'POST', headers, body: '{}' })]); $('#profileName').textContent = profile.display_name || 'DWGC2E 用户'; $('#profileEmail').textContent = profile.email || ''; $('#planName').textContent = subscription.plan_name || '免费版'; $('#usageUsed').textContent = Number(usage.used || 0).toLocaleString(); $('#usageQuota').textContent = Number(usage.monthly_quota || 0).toLocaleString(); $('#deviceCount').textContent = `${devices.used_devices || 0} / ${devices.max_devices || 3}`; const ratio = usage.monthly_quota ? Math.min(100, usage.used / usage.monthly_quota * 100) : 0; $('#usageBar').style.width = `${ratio}%`; authPanel.hidden = true; accountPanel.hidden = false; $('#accountStatus').textContent = '账户信息已同步。'; };
  form.addEventListener('submit', async e => { e.preventDefault(); const data = Object.fromEntries(new FormData(form)); if (data.password.length < 8) return message('密码至少需要 8 位。', true); const button = $('#authSubmit'); button.disabled = true; message(mode === 'login' ? '正在登录…' : '正在创建账号…'); try { if (mode === 'register') await request('/v1/auth/register', { method: 'POST', body: JSON.stringify(data) }); const login = mode === 'login' ? data : { account: data.account, password: data.password, device_id: `web-${crypto.randomUUID()}`, device_name: data.device_name || '网页端' }; const result = mode === 'login' ? await request('/v1/auth/login', { method: 'POST', body: JSON.stringify({ ...login, device_id: `web-${crypto.randomUUID()}`, device_name: data.device_name || '网页端' }) }) : await request('/v1/auth/login', { method: 'POST', body: JSON.stringify(login) }); sessionStorage.setItem(key, JSON.stringify({ token: result.token, expiresAt: result.expires_at })); await loadDashboard(result.token); } catch (err) { message(err.message || '请求失败，请稍后重试。', true); } finally { button.disabled = false; } });
  $('#logoutButton').addEventListener('click', () => { sessionStorage.removeItem(key); accountPanel.hidden = true; authPanel.hidden = false; $('#accountStatus').textContent = '已退出登录。'; setMode('login'); });
  try { const saved = JSON.parse(sessionStorage.getItem(key) || 'null'); if (saved?.token && (!saved.expiresAt || new Date(saved.expiresAt) > new Date())) loadDashboard(saved.token).catch(() => sessionStorage.removeItem(key)); else sessionStorage.removeItem(key); } catch { sessionStorage.removeItem(key); }
})();

