(() => {
 'use strict';
 const api=window.DWGC2E_API,$=s=>document.querySelector(s),money=n=>`¥${(n/100).toFixed(2)}`;
 const node=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};
 const say=(text,error=false)=>{$('#portalMessage').textContent=text;$('#portalMessage').className=`form-message${error?' error':''}`;};
 let current=null,timer=null,failures=0,busy=false,pending=null,nextCursor=null,stopped=false;
 let savedKey=null,authenticated=false;
 
 const validPending=p=>p&&typeof p==='object'&&typeof p.planId==='string'&&['alipay','wxpay'].includes(p.channel)&&typeof p.key==='string'&&/^[a-zA-Z0-9_-]{16,80}$/.test(p.key);
 if(pending&&!validPending(pending)){pending=null;try{sessionStorage.removeItem(savedKey);}catch{}}
 const save=()=>{if(!savedKey)return;try{if(pending)sessionStorage.setItem(savedKey,JSON.stringify(pending));else sessionStorage.removeItem(savedKey);}catch{}};
 const stop=()=>{clearTimeout(timer);timer=null;};
 const errorText={provider_query_http:'补充查单接口返回 HTTP 错误，请联系管理员',provider_query_redirect:'补充查单接口发生重定向，已安全拦截',provider_query_response:'补充查单返回格式异常，请联系管理员',provider_query_rejected:'平台未确认查单结果，请联系管理员',provider_query:'平台已响应，但订单补充查询未确认，请联系管理员核查',provider_prepare:'支付配置准备失败，请联系管理员',provider_network:'无法连接支付平台，请稍后重试',provider_redirect:'支付平台发生重定向，订单未取得二维码',provider_read:'读取支付平台响应失败',provider_parse:'支付平台返回格式错误',provider_business:'支付平台拒绝创建订单',provider_validation:'支付平台返回数据校验失败',provider_persist:'订单二维码保存失败，请联系管理员',provider_audit:'订单审计记录失败，请联系管理员',provider_timeout:'连接支付平台超时，请勿重复下单',provider_http:'支付平台返回 HTTP 错误',provider_response:'支付平台返回内容异常',provider_rejected:'支付平台拒绝创建订单',provider_signature_rejected:'平台拒绝签名，请核对商户配置',provider_channel_unavailable:'平台收款通道不可用',provider_amount_rejected:'平台拒绝订单金额',provider_merchant_rejected:'平台拒绝商户信息',provider_mismatch:'平台返回订单信息不匹配',provider_trade_missing:'平台未返回支付订单号',provider_amount_mismatch:'平台返回金额不一致',provider_qr_missing:'平台未返回二维码',invalid_qr_image:'平台二维码图片地址无效'};
 const statusText=o=>o.status==='paid'?'支付成功，Pro 已开通':o.createState==='unknown'?((o.providerMessage|| (o.errorCode&&errorText[o.errorCode]) ||'创建结果待确认，请勿重复付款，请联系管理员核查'))+(o.errorCode?'（'+o.errorCode+'）':''):o.createState==='creating'?'正在确认平台订单':o.status!=='pending'?o.status:'等待支付确认';
 async function member(){const [s,u]=await Promise.all([api.account.subscription(),api.account.usage()]);$('#membership').textContent=`当前套餐：${s.plan_name} · ${s.expires_at?'到期 '+new Date(s.expires_at).toLocaleString():'无付费有效期'} · 已用 ${Number(u.used).toLocaleString()} / ${Number(u.monthly_quota).toLocaleString()} 字符`;}
 function renderQr(o){
  const box=$('#qrBox');box.replaceChildren();
  if(o.status!=='pending'){box.append(node('p',o.status==='paid'?'订单已支付，无需再次扫码。':'当前订单不可继续付款。'));return;}
  if(o.createState!=='ready'){box.append(node('p',o.createState==='unknown'?'暂未获取到可用二维码，请勿重复下单或付款。':'正在确认平台订单，暂未获取二维码。'));return;}
  if(!Number.isFinite(Date.parse(o.expiresAt))||Date.parse(o.expiresAt)<=Date.now()){box.append(node('p','付款窗口已结束，请勿继续支付旧订单。'));return;}
  if(o.qrCode){try{const qr=qrcode(0,'M');qr.addData(o.qrCode);qr.make();const count=qr.getModuleCount(),scale=Math.max(2,Math.floor(240/(count+8))),canvas=document.createElement('canvas');canvas.width=canvas.height=(count+8)*scale;canvas.setAttribute('role','img');canvas.setAttribute('aria-label','支付二维码');const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';for(let y=0;y<count;y++)for(let x=0;x<count;x++)if(qr.isDark(y,x))ctx.fillRect((x+4)*scale,(y+4)*scale,scale,scale);box.append(canvas);return;}catch{/* Try the validated image fallback below. */}}
  if(o.qrCodeImageUrl){try{const url=new URL(o.qrCodeImageUrl);if(url.protocol!=='https:'||url.username||url.password)throw Error();const img=document.createElement('img');img.src=url.href;img.alt='支付二维码';img.referrerPolicy='no-referrer';img.onerror=()=>{if(current?.orderNo===o.orderNo)box.replaceChildren(node('p','二维码图片加载失败，请联系管理员。'));};box.append(img);return;}catch{box.append(node('p','二维码地址无效，请联系管理员。'));return;}}
  box.append(node('p',o.qrCode?'二维码生成失败，且没有可用备用图片，请联系管理员。':'服务器未返回二维码内容或图片地址，请联系管理员。'));
 }
 function show(o){stop();current=o;$('#checkout').hidden=false;$('#checkoutTitle').textContent=o.planName;$('#paymentAmount').textContent=money(o.payableCents);$('#paymentChannel').textContent=o.channel==='wxpay'?'请使用微信扫码':'请使用支付宝扫码';$('#orderNo').textContent=o.orderNo;$('#paymentStatus').textContent=statusText(o);const left=Math.max(0,Math.ceil((Date.parse(o.expiresAt)-Date.now())/1000));$('#countdown').textContent=left?`本地付款窗口剩余 ${Math.floor(left/60)} 分 ${left%60} 秒`:'付款窗口已结束。已付款请刷新状态，未付款请勿继续扫旧码。';if(o.status!=='pending'||o.createState!=='ready'||left<=0){$('#paymentChannel').textContent=o.channel==='wxpay'?'支付方式：微信':'支付方式：支付宝';if(o.status!=='pending'||o.createState!=='ready')$('#countdown').textContent='';}$('#scanHint').hidden=!(o.status==='pending'&&o.createState==='ready'&&left>0&&(o.qrCode||o.qrCodeImageUrl));renderQr(o);
  if(o.status==='paid'){if(pending?.orderNo===o.orderNo){pending=null;save();}member().catch(()=>say('支付成功，会员信息刷新失败，请稍后刷新。',true));}
  if(!stopped&&!document.hidden&&o.status==='pending'&&left>0)timer=setTimeout(refresh,Math.min(30000,3000*2**failures));
 }
 async function refresh(){if(!current)return;const no=current.orderNo;stop();try{const o=await api.billing.status(no);if(stopped||current?.orderNo!==no)return;failures=0;show(o);if(o.status==='paid')await orders();}catch(e){failures=Math.min(failures+1,4);say(e.message,true);if((e.authExpired || e.code==='unauthenticated')){stopped=true;$('#loginLink').hidden=false;}if(!stopped&&!document.hidden)timer=setTimeout(refresh,Math.min(30000,3000*2**failures));}}
 async function checkout(planId){if(busy)return;if(!authenticated){$('#loginLink').hidden=false;say('请先登录后再购买会员。',true);return;}if(pending&&(pending.planId!==planId||pending.channel!==$('input[name=channel]:checked').value)){if(!confirm('之前的订单可能仍有效。请先确认没有付款，是否创建新订单？'))return;pending=null;save();}
  busy=true;$('#plans').querySelectorAll('button').forEach(b=>b.disabled=true);try{if(!pending){pending={planId,channel:$('input[name=channel]:checked').value,key:crypto.randomUUID()};save();}const o=await api.billing.checkout({planId:pending.planId,channel:pending.channel},pending.key);pending.orderNo=o.orderNo;save();show(o);await orders();say(o.createState==='ready'?'请核对金额。付款后由服务器确认会员开通。':statusText(o),o.createState==='unknown');}catch(e){if(e.code==='order_hidden'){pending=null;save();say(e.message,true);}else if(e.code==='invalid_idempotency_key'){pending=null;save();say('下单标识未正确传递，已清理无效记录。请刷新页面后重新点击购买。',true);}else{say(e.message+'；重试将复用原下单标识。',true);}if((e.authExpired || e.code==='unauthenticated'))$('#loginLink').hidden=false;}finally{busy=false;$('#plans').querySelectorAll('button').forEach(b=>b.disabled=false);}}
 async function hideOrder(o,button){
  if(busy)return;
  if(!confirm('隐藏这条未付款订单记录？此操作不会取消平台订单，也不会退款。请确认没有付款；隐藏后不要再扫旧码。后台会保留对账记录。'))return;
  busy=true;button.disabled=true;
  try{
   await api.billing.hide(o.orderNo);
   if(pending?.orderNo===o.orderNo){pending=null;save();}
   if(current?.orderNo===o.orderNo){stop();current=null;$('#checkout').hidden=true;}
   await orders();say('订单记录已隐藏。确认没有付款后，可重新选择套餐创建新订单；请勿支付旧订单。');
  }catch(e){say(e.message,true);button.disabled=false;}
  finally{busy=false;}
 }
 async function orders(append=false){const d=await api.billing.orders(append?nextCursor:null);const box=$('#orderList');if(!append)box.replaceChildren();for(const o of d.orders){const row=node('div','','billing-order'),details=node('div',`${o.planName} · ${money(o.payableCents)} · ${statusText(o)}`);details.append(node('small',`${new Date(o.createdAt).toLocaleString()} · ${o.orderNo}`));const b=node('button','查看订单','btn btn-ghost');b.onclick=()=>{show(o);refresh();};row.append(details,b);if(o.status!=='paid'&&!o.paidAt){const del=node('button','隐藏记录','btn btn-ghost');del.onclick=()=>hideOrder(o,del);row.append(del);}box.append(row);}if(!box.children.length)box.textContent='暂无订单记录';nextCursor=d.nextCursor;$('#moreOrders').hidden=!nextCursor;}
 async function init(){try{const d=await api.billing.plans();say(d.message);for(const p of d.plans){const card=node('article',''),title=node('h2',p.name),desc=node('p',`Pro ${p.duration_days} 天 · 每月 100 万字符上限`),price=node('strong',money(p.price_cents)),b=node('button','立即购买','btn btn-primary');b.onclick=()=>checkout(p.id);card.append(title,desc,price,b);$('#plans').append(card);}const profile=await api.account.profile();if(!profile.user_id)throw new Error('无法确定账户身份，请重新登录。');authenticated=true;savedKey='dwgc2e.payment.pending.'+profile.user_id;try{pending=JSON.parse(sessionStorage.getItem(savedKey)||'null');}catch{}if(!validPending(pending))pending=null;await member();await orders();if(pending)say('检测到未完成下单。选择原套餐可安全重试，或从最近订单查看付款状态。');}catch(e){$('#membership').textContent='会员信息未能完成同步，请刷新页面重试。';if($('#orderList').textContent==='正在加载订单…')$('#orderList').textContent='订单尚未加载，请刷新页面重试。';say((e.authExpired || e.code==='unauthenticated')?'请先登录与 APP 相同的账号，再购买会员套餐。':e.message,true);if((e.authExpired || e.code==='unauthenticated'))$('#loginLink').hidden=false;}}
 $('#refreshOrder').onclick=refresh;$('#moreOrders').onclick=()=>orders(true).catch(e=>say(e.message,true));document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else refresh();});window.addEventListener('pagehide',()=>{stopped=true;stop();});window.addEventListener('pageshow',()=>{stopped=false;if(current)refresh();});init();
})();
