document.querySelectorAll('[data-back-button]').forEach(button => button.addEventListener('click', () => { if (window.history.length > 1) window.history.back(); else window.location.assign('account.html'); }));
(() => {
  'use strict';
  const session = (() => { try { return JSON.parse(sessionStorage.getItem('dwgc2e.session') || 'null'); } catch { return null; } })();
  const tokenValid = !!(session?.token && (!session.expiresAt || new Date(session.expiresAt) > new Date()));
  const message = document.querySelector('#portalMessage');
  const say = (text, error = false) => { if (message) { message.textContent = text || ''; message.className = `form-message${error ? ' error' : ''}`; } };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  if (!tokenValid) { say('请先登录后再访问此页面。', true); document.querySelectorAll('button[type="submit"], [data-integration-action], [data-revoke]').forEach(button => { button.disabled = true; }); const card = document.querySelector('.portal-card'); if (card && !card.querySelector('.portal-login-link')) { const link = document.createElement('a'); link.className = 'btn btn-primary portal-login-link'; link.href = `account.html?return=${encodeURIComponent(location.pathname.split('/').pop() || 'account.html')}`; link.textContent = '前往登录'; card.append(link); } return; }
  document.querySelectorAll('[data-integration-action]').forEach(button => button.addEventListener('click', async () => { say('正在连接服务…'); button.disabled = true; try { const result = await window.DWGC2E_API.billing.checkout({ plan_id: button.dataset.planId || button.dataset.integrationAction }); const url = result?.checkout_url || result?.url; if (url && /^https:\/\//i.test(url)) { location.assign(url); return; } say('支付接口已返回，但未提供安全的支付地址。', true); } catch (error) { say(error.status === 404 ? '套餐支付接口暂未开放，当前不会产生订单。' : (error.message || '暂时无法创建订单。'), true); } finally { button.disabled = false; } }));
  const planCards = document.querySelectorAll('[data-plan-card]'); if (planCards.length) window.DWGC2E_API.billing.plans().then(data => { const plans = Array.isArray(data) ? data : (data?.plans || data?.items || []); plans.forEach(plan => { const card = [...planCards].find(item => item.dataset.planId === String(plan.id)); if (!card) return; const price = card.querySelector('strong'); if (price && plan.price != null) price.textContent = plan.price === 0 ? '¥0' : `¥${esc(plan.price)}`; const desc = card.querySelector('p'); if (desc && plan.description) desc.textContent = plan.description; }); }).catch(() => {});
  const orderList = document.querySelector('#orderList'); if (orderList) window.DWGC2E_API.billing.orders().then(data => { const orders = Array.isArray(data) ? data : (data?.orders || data?.items || []); orderList.className = orders.length ? 'order-list' : 'portal-empty'; orderList.innerHTML = orders.length ? orders.map(order => `<div class="order-row"><span>${esc(order.plan_name || order.plan_id || '套餐订单')}</span><span>${esc(order.status || '处理中')}</span><time>${esc(order.created_at || '—')}</time></div>`).join('') : '暂无订单记录。'; }).catch(error => { orderList.className = 'portal-empty'; orderList.textContent = error.status === 404 ? '订单接口暂未开放。' : '订单暂时无法读取。'; });
  const list = document.querySelector('#deviceList'); if (list) window.DWGC2E_API.deviceManagement.list().then(data => { const devices = Array.isArray(data) ? data : (data?.devices || data?.items || []); list.innerHTML = devices.length ? devices.map(device => { const id = String(device.device_id || device.id || ''); return `<div class="device-row"><div><strong>${esc(device.device_name || device.name || '未命名设备')}</strong><span>${esc(device.platform || 'Windows')} · ${esc(device.last_seen_at || '已绑定')}</span></div>${id ? `<button class="btn btn-ghost btn-sm" data-revoke="${esc(id)}">解除绑定</button>` : '<span>当前设备</span>'}</div>`; }).join('') : '<div class="portal-empty">暂无已绑定设备。</div>'; list.querySelectorAll('[data-revoke]').forEach(button => button.addEventListener('click', async () => { if (!confirm('确定解除这台设备吗？')) return; button.disabled = true; try { await window.DWGC2E_API.deviceManagement.revoke(button.dataset.revoke); button.closest('.device-row').remove(); say('设备已解除绑定。'); } catch (error) { button.disabled = false; say(error.status === 404 ? '设备解绑接口暂未开放。' : (error.message || '设备解绑失败。'), true); } })); }).catch(error => { list.innerHTML = '<div class="portal-empty">设备列表暂时无法读取。</div>'; say(error.status === 404 ? '设备列表接口暂未开放。' : '设备列表读取失败。', true); });
  const profileForm = document.querySelector('#profileForm'); if (profileForm) { window.DWGC2E_API.account.profile().then(data => { profileForm.elements.display_name.value = data?.display_name || ''; profileForm.elements.email.value = data?.email || data?.account || ''; }).catch(() => say('账户信息暂时无法读取。', true)); profileForm.addEventListener('submit', async event => { event.preventDefault(); const button = profileForm.querySelector('button[type="submit"]'); button.disabled = true; try { await window.DWGC2E_API.profileManagement.update(Object.fromEntries(new FormData(profileForm))); say('资料已保存。'); } catch (error) { say(error.status === 404 ? '资料保存接口暂未开放，尚未保存任何修改。' : (error.message || '资料保存失败。'), true); } finally { button.disabled = false; } }); }
  const passwordForm = document.querySelector('#passwordForm'); if (passwordForm) passwordForm.addEventListener('submit', async event => { event.preventDefault(); const msg = document.querySelector('#passwordMessage'), button = passwordForm.querySelector('button[type="submit"]'); if (passwordForm.new_password.value.length < 8 || passwordForm.new_password.value !== passwordForm.confirm_password.value) { msg.textContent = '请确认两次输入一致，且新密码至少 8 位。'; msg.className = 'form-message error'; return; } button.disabled = true; try { await window.DWGC2E_API.profileManagement.changePassword(Object.fromEntries(new FormData(passwordForm))); msg.textContent = '密码已修改，请重新登录。'; msg.className = 'form-message'; } catch (error) { msg.textContent = error.status === 404 ? '密码修改接口暂未开放。' : (error.message || '密码修改失败。'); msg.className = 'form-message error'; } finally { button.disabled = false; } });
})();

