(async () => {
  'use strict';
  let profile;try { profile=await window.DWGC2E_API.account.profile(); } catch { location.replace('account.html?return=terminology.html');return; }
  if(!profile.user_id){location.replace('account.html?return=terminology.html');return;}
  const key = 'dwgc2e.glossary.'+profile.user_id;
  const seed = [];
  const $ = selector => document.querySelector(selector);
  const list = $('#glossaryList'), search = $('#glossarySearch'), form = $('#glossaryForm'), msg = $('#glossaryMessage'), selectAll = $('#selectAll');
  if (!list || !search || !form || !msg || !selectAll) return;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const read = () => { try { const value = JSON.parse(localStorage.getItem(key) || 'null'); return Array.isArray(value) ? value : seed.slice(); } catch { return seed.slice(); } };
  const save = () => { try { localStorage.setItem(key, JSON.stringify(rows)); return true; } catch { return false; } };
  const say = (text, error = false) => { msg.textContent = text || ''; msg.className = `form-message${error ? ' error' : ''}`; };
  let rows = read(), editingId = '';
  const visibleRows = () => { const query = search.value.trim().toLowerCase(); return rows.filter(row => [row.source, row.target, row.note].join(' ').toLowerCase().includes(query)); };
  const render = () => {
    const shown = visibleRows();
    list.innerHTML = shown.length ? shown.map(row => `<tr><td><input type="checkbox" data-check="${esc(row.id)}" aria-label="选择 ${esc(row.source)}"></td><td>${esc(row.source)}</td><td>${esc(row.target)}</td><td>${esc(row.note || '—')}</td><td><button type="button" class="btn btn-ghost btn-sm" data-edit="${esc(row.id)}">编辑</button> <button type="button" class="btn btn-ghost btn-sm" data-delete="${esc(row.id)}">删除</button></td></tr>`).join('') : '<tr><td colspan="5" class="table-empty">暂无匹配词条。</td></tr>';
    $('#glossaryCount').textContent = `显示 ${shown.length} / 共 ${rows.length} 条`;
    selectAll.checked = shown.length > 0 && shown.every(row => list.querySelector(`[data-check="${CSS.escape(row.id)}"]`)?.checked);
    selectAll.indeterminate = false;
  };
  const resetForm = () => { editingId = ''; form.reset(); $('#saveGlossary').textContent = '添加词条'; $('#cancelGlossary').hidden = true; };
  form.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const source = String(data.source || '').trim(), target = String(data.target || '').trim(), note = String(data.note || '').trim(); if (!source || !target) return say('请填写原文和译文。', true); const duplicate = rows.find(row => row.source.toLowerCase() === source.toLowerCase() && row.id !== editingId); if (duplicate) return say('原文术语已存在，请直接编辑已有词条。', true); if (editingId) { const row = rows.find(item => item.id === editingId); if (row) Object.assign(row, { source, target, note }); say('词条已更新并保存到本机。'); } else { rows.unshift({ id: `local-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, source, target, note }); say('词条已保存到本机。'); } save(); resetForm(); render(); });
  $('#cancelGlossary').addEventListener('click', () => { resetForm(); render(); say('已取消编辑。'); });
  list.addEventListener('click', event => { const edit = event.target.closest('[data-edit]'); if (edit) { const row = rows.find(item => item.id === edit.dataset.edit); if (row) { editingId = row.id; form.elements.source.value = row.source; form.elements.target.value = row.target; form.elements.note.value = row.note || ''; $('#saveGlossary').textContent = '保存修改'; $('#cancelGlossary').hidden = false; form.elements.source.focus(); say('正在编辑词条。'); } return; } const remove = event.target.closest('[data-delete]'); if (!remove) return; if (!confirm('确定删除这条词汇吗？')) return; rows = rows.filter(row => row.id !== remove.dataset.delete); save(); render(); say('词条已删除。'); });
  search.addEventListener('input', render);
  selectAll.addEventListener('change', () => { list.querySelectorAll('[data-check]').forEach(input => { input.checked = selectAll.checked; }); selectAll.indeterminate = false; });
  $('#deleteSelected').addEventListener('click', () => { const ids = [...list.querySelectorAll('[data-check]:checked')].map(input => input.dataset.check); if (!ids.length) return say('请先选择要删除的词条。', true); if (!confirm(`确定删除选中的 ${ids.length} 条词汇吗？`)) return; rows = rows.filter(row => !ids.includes(row.id)); save(); render(); say(`已删除 ${ids.length} 条词汇。`); });
  $('#exportGlossary').addEventListener('click', () => { const blob = new Blob([JSON.stringify(rows, null, 2)], { type: 'application/json' }), url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = 'dwgc2e-glossary.json'; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 0); say('词汇表已导出。'); });
  $('#importGlossary').addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const raw = String(reader.result || ''), data = file.name.toLowerCase().endsWith('.csv') ? parseCsv(raw) : JSON.parse(raw); if (!Array.isArray(data)) throw Error(); const imported = data.filter(item => item && item.source && item.target).map(item => ({ id: `local-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, source: String(item.source).trim(), target: String(item.target).trim(), note: String(item.note || '').trim() })); const existing = new Set(rows.map(row => row.source.toLowerCase())); const fresh = imported.filter(item => !existing.has(item.source.toLowerCase())); rows = [...fresh, ...rows]; save(); render(); say(`已导入 ${fresh.length} 条新词汇，重复项已跳过。`); } catch { say('导入失败，请选择有效的 JSON 或 CSV 词汇表。', true); } finally { event.target.value = ''; } }; reader.readAsText(file); });
  function parseCsv(raw) { const lines = raw.split(/\r?\n/).filter(line => line.trim()); if (!lines.length) return []; const cells = line => { const result = [], regex = /("(?:[^"]|"")*"|[^,]*)/g; let match; while ((match = regex.exec(line)) && match[0] !== '') { let value = match[1] || ''; if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1).replace(/""/g, '"'); result.push(value.trim()); if (line[regex.lastIndex] === ',') regex.lastIndex++; else break; } return result; }; const header = cells(lines.shift()).map(value => value.toLowerCase()); return lines.map(line => { const values = cells(line); return { source: values[header.indexOf('source')] || values[0], target: values[header.indexOf('target')] || values[1], note: values[header.indexOf('note')] || values[2] || '' }; }); }
  $('#syncGlossary').addEventListener('click', async () => { const button = $('#syncGlossary'); button.disabled = true; say('正在读取云端词库…'); try { const data = await window.DWGC2E_API.terminology.list(); const cloud = Array.isArray(data) ? data : (data?.items || data?.terminology || data?.glossaries || []); if (!Array.isArray(cloud)) throw Error('云端返回格式无效'); const existing = new Set(rows.map(row => `${row.source.toLowerCase()}\u0000${row.target.toLowerCase()}`)); const additions = cloud.filter(item => item?.source && item?.target && !existing.has(`${String(item.source).toLowerCase()}\u0000${String(item.target).toLowerCase()}`)).map(item => ({ id: String(item.id || `cloud-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`), source: String(item.source), target: String(item.target), note: String(item.note || '') })); rows = [...additions, ...rows]; save(); render(); say(`云端已连接，新增合并 ${additions.length} 条词汇。`); } catch (error) { say(error.status === 404 ? '云端词库接口暂未开放，当前词条仍保存在本机。' : (error.message || '云端同步失败。'), true); } finally { button.disabled = false; } });
  render();
})();
