(() => {
'use strict';
const key='dwgc2e.glossary', seed=[{id:'local-1',source:'Floor Plan',target:'平面图',note:'建筑图纸常用术语'},{id:'local-2',source:'Elevation',target:'立面图',note:''}];
const read=()=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return Array.isArray(v)?v:seed}catch{return seed}}; let rows=read(); let editingId=''; const save=()=>{try{localStorage.setItem(key,JSON.stringify(rows))}catch{}};
const $=s=>document.querySelector(s), list=$('#glossaryList'), search=$('#glossarySearch'), form=$('#glossaryForm'), msg=$('#glossaryMessage'), selectAll=$('#selectAll'); const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const say=(t,e=false)=>{msg.textContent=t;msg.className='form-message'+(e?' error':'')};
const render=()=>{const q=(search.value||'').trim().toLowerCase(), shown=rows.filter(r=>[r.source,r.target,r.note].join(' ').toLowerCase().includes(q)); list.innerHTML=shown.length?shown.map(r=>`<tr><td><input type="checkbox" data-check="${esc(r.id)}"></td><td>${esc(r.source)}</td><td>${esc(r.target)}</td><td>${esc(r.note||'—')}</td><td><button type="button" class="btn btn-ghost btn-sm" data-edit="${esc(r.id)}">编辑</button><button type="button" class="btn btn-ghost btn-sm" data-delete="${esc(r.id)}">删除</button></td></tr>`).join(''):'<tr><td colspan="5" class="table-empty">暂无匹配词条。</td></tr>'; selectAll.checked=false;$('#glossaryCount').textContent=`共 ${shown.length} 条`};
form.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form));if(!d.source.trim()||!d.target.trim())return say('请填写原文和译文。',true);if(editingId){const item=rows.find(r=>r.id===editingId);if(item)Object.assign(item,{source:d.source.trim(),target:d.target.trim(),note:d.note.trim()});editingId='';$('#saveGlossary').textContent='添加词条';$('#cancelGlossary').hidden=true;say('词条已更新。')}else{rows.unshift({id:'local-'+Date.now(),source:d.source.trim(),target:d.target.trim(),note:d.note.trim()});say('词条已保存到本机，后续可切换为云端同步。')}save();form.reset();render()});
$('#cancelGlossary').addEventListener('click',()=>{editingId='';form.reset();$('#saveGlossary').textContent='添加词条';$('#cancelGlossary').hidden=true;say('已取消编辑。')});
list.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]');if(edit){const item=rows.find(r=>r.id===edit.dataset.edit);if(item){editingId=item.id;form.source.value=item.source;form.target.value=item.target;form.note.value=item.note||'';$('#saveGlossary').textContent='保存修改';$('#cancelGlossary').hidden=false;form.source.focus();say('正在编辑词条。')}return}const b=e.target.closest('[data-delete]');if(!b)return;if(!confirm('确定删除这条词汇吗？'))return;rows=rows.filter(r=>r.id!==b.dataset.delete);save();render();say('词条已删除。')}); search.addEventListener('input',render); selectAll.addEventListener('change',()=>list.querySelectorAll('[data-check]').forEach(x=>x.checked=selectAll.checked));
$('#syncGlossary').addEventListener('click',async()=>{const b=$('#syncGlossary');b.disabled=true;say('正在同步云端…');try{if(!window.DWGC2E_API)throw Error('未配置 API');await window.DWGC2E_API.terminology.list();say('云端词库接口已连接；批量同步接口待 Worker 开放。')}catch(error){say(error.status===404?'云端词库接口暂未开放，当前词条仍安全保存在本机。':(error.message||'云端同步失败。'),true)}finally{b.disabled=false}});
$('#deleteSelected').addEventListener('click',()=>{const ids=[...list.querySelectorAll('[data-check]:checked')].map(x=>x.dataset.check);if(!ids.length)return say('请先选择要删除的词条。',true);if(!confirm(`确定删除选中的 ${ids.length} 条词汇吗？`))return;rows=rows.filter(r=>!ids.includes(r.id));save();render();say('选中词条已删除。')});
$('#exportGlossary').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dwgc2e-glossary.json';a.click();URL.revokeObjectURL(a.href);say('词汇表已导出。')});
$('#importGlossary').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data))throw Error();rows=data.filter(x=>x&&x.source&&x.target).map(x=>({id:x.id||'local-'+Date.now()+Math.random(),source:String(x.source),target:String(x.target),note:String(x.note||'')}));save();render();say(`已导入 ${rows.length} 条词汇。`)}catch{say('导入失败，请选择有效的 JSON 词汇表。',true)}e.target.value=''};reader.readAsText(file)}); render();
})();
