// Isolated regression adapter: serve unchanged local bytes in browser routes, avoiding exhausted Windows loopback sockets.
const fs=require('fs'),path=require('path'),http=require('http');
const siteRoot=path.resolve(__dirname,'..');
const createServer=http.createServer;http.createServer=(...args)=>{const s=createServer(...args);s.listen=(...a)=>{queueMicrotask(()=>{s.emit('listening');if(typeof a.at(-1)==='function')a.at(-1)()});return s};s.address=()=>({port:8091,address:'127.0.0.1'});s.close=cb=>{cb?.();return s};return s};
function local(route){const u=new URL(route.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)&&!u.pathname.startsWith('/api/')}
function wrap(target){const register=target.route.bind(target);target.route=(pattern,handler,...rest)=>register(pattern,async route=>{const original=route.continue.bind(route);route.continue=(...args)=>local(route)?serve(route):original(...args);return handler(route)},...rest);}
const {chromium}=require(process.env.PLAYWRIGHT_MODULE);const launch=chromium.launch.bind(chromium);
chromium.launch=async options=>{const browser=await launch(options);const create=browser.newContext.bind(browser);browser.newContext=async options=>{const ctx=await create(options);wrap(ctx);await ctx.route('**/*',route=>local(route)?serve(route):route.fallback());const page=ctx.newPage.bind(ctx);ctx.newPage=async()=>{const p=await page();wrap(p);return p};return ctx};browser.newPage=async options=>{const ctx=await browser.newContext(options);return ctx.newPage()};return browser};
function serve(route){let p=new URL(route.request().url()).pathname;if(p==='/')p='/index.html';else if(!path.extname(p))p+='.html';const f=path.resolve(siteRoot,'.'+decodeURIComponent(p));if(!f.startsWith(siteRoot+path.sep))return route.abort();return route.fulfill({status:fs.existsSync(f)?200:404,contentType:({'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.woff2':'font/woff2'})[path.extname(f)]||'application/octet-stream',body:fs.existsSync(f)?fs.readFileSync(f):'Not found'})}
