// Local-only browser + real Worker/SQLite acceptance. Never contacts production or payment providers.
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {pathToFileURL}=require('node:url'),{DatabaseSync}=require('node:sqlite');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),workerRoot=process.env.WORKER_ROOT||path.resolve(root,'../DWGC2E/cf-worker');let server,browser,origin,db,worker,env;const key='local-admin-test-'.repeat(4);
before(async()=>{
 worker=(await import(pathToFileURL(path.join(workerRoot,'src/index.ts')))).default;
 db=new DatabaseSync(':memory:');db.exec(fs.readFileSync(path.join(workerRoot,'schema.sql'),'utf8'));
 db.prepare("INSERT INTO users(id,account,email,password_hash,created_at) VALUES('local-user','local-engineer','local@example.test','unused',?)").run(new Date().toISOString());
 const DB={prepare(sql){return {sql,values:[],bind(...v){this.values=v;return this;},async first(){return db.prepare(sql).get(...this.values)||null;},async all(){return {results:db.prepare(sql).all(...this.values)};},async run(){return {success:true,meta:{changes:Number(db.prepare(sql).run(...this.values).changes)}};}}},async batch(items){db.exec('BEGIN');try{const rows=items.map(s=>{const q=db.prepare(s.sql);return q.columns().length?{success:true,results:q.all(...s.values)}:{success:true,meta:{changes:Number(q.run(...s.values).changes)}}});db.exec('COMMIT');return rows;}catch(e){db.exec('ROLLBACK');throw e;}}};env={DB,ADMIN_API_KEY:key,PAYMENTS_ENABLED:'false',LATEST_VERSION:'2.1.0',PASSWORD_PEPPER:'local-only'};
 server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local');if(url.pathname.startsWith('/api/')){const chunks=[];for await(const c of req)chunks.push(c);const r=await worker.fetch(new Request('https://local.test'+url.pathname.slice(4)+url.search,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})}),env);res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()));return;}
 const file=path.resolve(root,'.'+url.pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'content-type':({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream'});res.end(e?'missing':b);});}catch(e){res.writeHead(500);res.end(String(e));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;env.CORS_ORIGINS=origin;browser=await chromium.launch({channel:'msedge',headless:true});
});after(async()=>{await browser?.close();await new Promise(r=>server.close(r));db?.close();});
for(const width of [390,1440])test('operations complete local integration '+width,async t=>{
 const beforeBonus=Number(db.prepare('SELECT SUM(amount) n FROM quota_compensations_v3').get().n||0);const context=await browser.newContext({viewport:{width,height:1000},timezoneId:'Asia/Shanghai'});const p=await context.newPage();t.after(()=>context.close());p.setDefaultTimeout(15000);const errors=[];p.on('pageerror',e=>{errors.push(e.message);console.error('BROWSER',e.message);});p.on('response',async r=>{if(r.status()>=400)console.error('HTTP',r.status(),r.url(),await r.text().catch(()=>''));});t.after(async()=>{if(t.passed===false)console.error('UI',await p.locator('#detailMessage').textContent().catch(()=>''),await p.locator('#userMessage').textContent().catch(()=>''));});await p.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());p.on('dialog',d=>d.accept());
 await p.goto(origin+'/admin-users.html');await p.locator('#userKey').fill(key);await p.locator('#userLogin button').click();await p.locator('#userWorkspace:visible').waitFor();const cookies=await p.context().cookies();assert.ok(cookies.some(c=>c.name==='__Secure-dwgc_admin'&&c.httpOnly&&c.secure));assert.equal(await p.evaluate(()=>document.cookie.includes('dwgc_admin')),false);await p.route('**/api/v1/admin/session',async r=>{if(r.request().method()==='GET')await new Promise(resolve=>setTimeout(resolve,500));await r.continue();});await p.reload({waitUntil:'domcontentloaded'});assert.equal(await p.locator('#userGate').isVisible(),false);await p.locator('#userWorkspace:visible').waitFor();
 const tab=async name=>{await p.getByRole('navigation',{name:'后台模块'}).getByRole('link',{name,exact:true}).click();await p.locator('#userWorkspace:visible').waitFor();await p.waitForFunction(()=>!document.querySelector('#opsRefresh').disabled);assert.equal(await p.locator('#userGate').isVisible(),false);assert.equal(await p.locator('nav[aria-label=后台模块]').count(),1);assert.equal(await p.locator('#opsTabs').count(),0);};
 await tab('套餐与额度');await p.locator('.plan-config[data-plan=go]').waitFor();const go=p.locator('.plan-config[data-plan=go]');await go.locator('[name=price]').fill('1.00');await go.locator('[name=quota]').fill('54321');await go.locator('[name=displayName]').fill('Go 加量包');await go.locator('[name=description]').fill('额外额度，30 天内有效');await go.locator('[name=enabled]').check();await go.locator('[name=reason]').fill('调');await go.locator('button[type=submit]').click();await p.waitForFunction(()=>document.querySelector('#planMessage').textContent.startsWith('已保存'));assert.equal(db.prepare("SELECT quota FROM plan_catalog WHERE id='go'").get().quota,54321);
 const out=process.env.AUDIT_OUTPUT;if(out){fs.mkdirSync(out,{recursive:true});await p.screenshot({path:path.join(out,'plans-admin-'+width+'.png'),fullPage:true});}
 await tab('软件发布');await p.locator('[name=latest_version]').fill('2.1.1+local.test');await p.locator('[name=download_url]').fill('https://example.com/test-package.zip');await p.locator('[name=backup_download_url]').fill('https://example.com/backup.zip');await p.locator('[name=release_notes]').fill('本地验收版本；不会上传安装包。');await p.locator('#opsContent [name=reason]').fill('改');await p.locator('#opsContent button[type=submit]').click();await p.waitForFunction(()=>document.querySelector('#opsMessage').textContent.startsWith('已保存'));if(out)await p.screenshot({path:path.join(out,'release-admin-'+width+'.png'),fullPage:true});
 const storedContent=JSON.parse(db.prepare("SELECT value_json FROM operation_settings WHERE section='content'").get().value_json);storedContent.headline='ceshi';storedContent.description='ceshi';db.prepare("UPDATE operation_settings SET value_json=? WHERE section='content'").run(JSON.stringify(storedContent));
 await tab('公告与帮助');assert.equal(await p.locator('[name=headline], [name=description]').count(),0);await p.locator('[name=announcement]').fill('<img src=x onerror=alert(1)> 公告纯文本测试');await p.locator('[name=help_text]').fill('第一步：安装软件。\n第二步：登录账户。');await p.locator('[name=contact_email]').fill('support@example.com');await p.locator('#opsContent [name=reason]').fill('本地验证公告与帮助内容');await p.locator('#opsContent button[type=submit]').click();await p.waitForFunction(()=>document.querySelector('#opsMessage').textContent.startsWith('已保存'));
 await tab('功能开关');await p.locator('[name=device_wait_days]').fill('5');await p.locator('#opsContent [name=reason]').fill('本地验证设备解绑规则');await p.locator('#opsContent button[type=submit]').click();await p.waitForFunction(()=>document.querySelector('#opsMessage').textContent.startsWith('已保存'));
 const stamp=new Date().toISOString(),device='local-device-'+width;
 db.prepare('INSERT INTO app_device_bindings(user_id,device_id,device_name,first_seen,last_seen,revoked) VALUES(?,?,?,?,?,0)').run('local-user',device,'本地验收设备',stamp,stamp);
 await tab('设备管理');const record=p.locator('.ops-record').filter({hasText:device});await record.getByRole('textbox',{name:'强制解绑原因'}).fill('管理员即时换机');
 if(out)await p.screenshot({path:path.join(out,'devices-admin-'+width+'.png'),fullPage:true});
 await record.getByRole('button',{name:'立即强制解绑',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#opsMessage').textContent.includes('设备已强制解绑'));
 assert.equal(db.prepare('SELECT revoked FROM app_device_bindings WHERE device_id=?').get(device).revoked,1);
 assert.equal(db.prepare('SELECT reason FROM admin_device_revocations WHERE device_id=?').get(device).reason,'管理员即时换机');
 for(const name of ['订单售后','设备管理','用户反馈','操作记录']){await tab(name);assert.equal(await p.locator('#opsMessage').textContent(),'');}
 await tab('用户管理');await p.getByRole('button',{name:'查看详情',exact:true}).click();await p.locator('#detailContent:visible').waitFor();await p.locator('#editPlan').selectOption('max');await p.locator('#editExpiry').fill('2099-01-01T08:00');await p.locator('#editReason').fill('升');db.prepare("UPDATE plan_catalog SET quota=2000000 WHERE id='max'").run();await p.locator('#saveMembership').click();await p.waitForFunction(()=>document.querySelector('#detailMessage').textContent.includes('会员修改已保存'));assert.equal(db.prepare("SELECT plan_name FROM subscriptions WHERE user_id='local-user'").get().plan_name,'max');await p.locator('#compensationEditor input').fill('100');await p.locator('#compensationEditor textarea').fill('补');await p.locator('#compensationEditor button').click();await p.waitForFunction(n=>document.querySelector('#compensationEditor p').textContent.includes('当前本月补偿：'+n+' 字符'),beforeBonus+100);await p.waitForFunction(()=>!document.querySelector('#saveMembership').disabled);assert.equal(db.prepare('SELECT SUM(amount) n FROM quota_compensations_v3').get().n,beforeBonus+100);await p.locator('#detailClose').click();
 await tab('用量明细');await p.locator('#opsContent input').fill('local-user');await p.locator('#opsContent button[type=submit]').click();await p.getByRole('heading',{name:'本月与历史补偿记录'}).waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
 const other=await p.context().newPage();await other.goto(origin+'/admin-feedback.html');await other.locator('#userWorkspace:visible').waitFor();await tab('用户管理');await p.locator('#userLogout').click();await other.locator('#userGate:visible').waitFor();assert.equal(await other.locator('#userWorkspace').isVisible(),false);await other.close();assert.equal(await p.locator('#userWorkspace').isVisible(),false);assert.equal(await p.locator('#opsContent').textContent(),'');assert.equal(await p.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.deepEqual(errors,[]);
 const home=await browser.newPage({viewport:{width,height:1000}});t.after(()=>home.close());await home.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await home.goto(origin+'/index.html');await home.waitForFunction(()=>document.querySelector('[data-version]').textContent==='2.1.1+local.test');for(const a of await home.locator('[data-download]').all())assert.equal(await a.getAttribute('href'),'https://example.com/test-package.zip');assert.equal(await home.locator('.hero-copy h1').textContent(),'图纸有边界，沟通不必有。');assert.equal(await home.locator('.hero-copy h1 .hand-underline').textContent(),'不必有。');assert.match(await home.locator('.hero-lead').textContent(),/让工程语言，回到图纸里。/);assert.equal(await home.locator('#siteAnnouncement img').count(),0);assert.match(await home.locator('#siteAnnouncement').textContent(),/公告纯文本测试/);assert.equal(await home.locator('#managedHelp').count(),1);assert.equal(await home.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);if(out)await home.screenshot({path:path.join(out,'managed-home-'+width+'.png'),fullPage:false});
});

