import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const code=readFileSync(new URL('../functions/api/[[path]].js',import.meta.url),'utf8').replace('export async function','async function');
function setup(fetch){const ctx={URL,Headers,Response,AbortSignal,fetch};vm.runInNewContext(code+';globalThis.proxy=onRequest;',ctx);return ctx.proxy;}
test('proxy blocks unrelated admin endpoints and payment notifications',async()=>{const proxy=setup(()=>{throw Error('must not forward')});for(const path of ['/v1/admin/users','/v1/billing/notify/ezfpy'])assert.equal((await proxy({request:new Request('https://site.test/api'+path)})).status,404);});
test('feedback administration forwards credential only to fixed upstream and preserves server denial',async()=>{const proxy=setup(async(url,options)=>{assert.equal(url,'https://dwgc2e-api.maplehousezz.workers.dev/v1/admin/feedback');assert.equal(options.headers.get('authorization'),'Bearer ordinary-account-token');assert.equal(options.headers.get('x-admin-role'),null);assert.equal(options.headers.get('x-forwarded-for'),null);return Response.json({message:'管理员验证失败'},{status:401})});const response=await proxy({request:new Request('https://site.test/api/v1/admin/feedback',{headers:{authorization:'Bearer ordinary-account-token','x-admin-role':'admin','x-forwarded-for':'spoofed'}})});assert.equal(response.status,401);});
test('admin write path and method are restricted to feedback UUID status operation',async()=>{let forwarded=0;const proxy=setup(async()=>{forwarded++;return Response.json({success:true})});const id='12345678-1234-1234-1234-123456789012';assert.equal((await proxy({request:new Request('https://site.test/api/v1/admin/feedback/'+id,{method:'POST',body:'{}'})})).status,200);assert.equal((await proxy({request:new Request('https://site.test/api/v1/admin/feedback/'+id,{method:'DELETE'})})).status,404);assert.equal(forwarded,1);});
test('upstream redirects never send admin bearer to a redirected destination',async()=>{const proxy=setup(async()=>new Response(null,{status:302,headers:{location:'https://untrusted.test/'}}));assert.equal((await proxy({request:new Request('https://site.test/api/v1/admin/feedback')})).status,502);});
