const {test,before,after}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');let server,browser,origin;
before(async()=>{server=http.createServer((req,res)=>{let pathname=new URL(req.url,'http://localhost').pathname;if(!path.extname(pathname))pathname+='.html';const file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'content-type':({'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream'});res.end(e?'Not found':b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({channel:'msedge',headless:true});});
after(async()=>{await browser.close();await new Promise(r=>server.close(r));});
const fixture={id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',status:'new',email:'person@example.test',category:'suggestion',message:'希望改进资料设置页面的体验。',page:'/profile',created_at:'2026-09-15T00:00:00Z'};
async function pageFor(t,file,options={}){const p=await browser.newPage({viewport:{width:options.width||390,height:900},reducedMotion:'reduce'});p.setDefaultTimeout(5000);const errors=[];p.on('pageerror',e=>errors.push(e.message));t.after(async()=>{await p.close();assert.deepEqual(errors,[]);});if(options.session!==false)await p.addInitScript(()=>sessionStorage.setItem('dwgc2e.session',JSON.stringify({token:'mock-session',userId:'mock-user',expiresAt:'2099-01-01'})));await p.route('**/*',async r=>{const u=new URL(r.request().url());if(u.origin!==origin)return r.abort();if(!u.pathname.startsWith('/api/'))return r.continue();if(options.api&&await options.api(u,r))return;const responses={'/api/v1/profile':{display_name:'测试工程师',email:'person@example.test'},'/api/v1/health':{api:'operational',database:'operational'},'/api/v1/devices':{devices:[]},'/api/v1/admin/feedback':{items:[fixture],nextCursor:null},'/api/v1/translation/history':{items:[],nextCursor:null}};return r.fulfill({json:responses[u.pathname]||{success:true}});});await p.goto(origin+'/'+file);return p;}
async function adminLogin(p){await p.locator('#adminKey').fill('mock-admin-key-'.repeat(4));await p.locator('#adminLogin button').click();await p.locator('#adminWorkspace:visible').waitFor();}
function noOverflow(p){return p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1);}
for(const file of ['billing.html','status.html'])test(file+' health colors, failure, recovery and alignment',async t=>{let mode='ok';const p=await pageFor(t,file,{width:1440,api:async(u,r)=>{if(u.pathname.endsWith('/health')){if(mode==='network'){await r.abort();return true;}await r.fulfill({status:mode==='db'?503:200,json:{api:'operational',database:mode==='db'?'unavailable':'operational'}});return true;}if(u.pathname.endsWith('/profile')){await r.fulfill({json:{user_id:'mock-user',email:'new@example.test'}});return true;}if(u.pathname.endsWith('/plans')){await r.fulfill({json:{plans:[],paymentsEnabled:false,message:'购买服务暂未开放'}});return true;}if(u.pathname.endsWith('/entitlements')){await r.fulfill({json:{subscription:{plan_name:'free'},usage:{used:0,monthly_quota:100000}}});return true;}if(u.pathname.endsWith('/orders')){await r.fulfill({json:{orders:[],nextCursor:null}});return true;}return false;}});const root=file==='billing.html'?'.ws-status':'#statusList',retry=file==='billing.html'?'#wsRecheck':'#retryStatus';await p.locator(root+' [data-state=ok]').last().waitFor();await p.waitForFunction(s=>document.querySelector(s).disabled===false,retry);assert.equal(await p.locator(root+' [data-state=ok]').first().evaluate(e=>getComputedStyle(e).color),'rgb(40, 116, 68)');mode='db';await p.locator(retry).click();await p.locator(root+' [data-state=bad]').waitFor();mode='network';await p.locator(retry).click();await p.waitForFunction(s=>document.querySelector(s).disabled===false,retry);assert.equal(await p.locator(root+' [data-state=bad]').count(),0);mode='ok';await p.locator(retry).click();await p.waitForFunction(s=>document.querySelector(s).disabled===false,retry);if(file==='billing.html'){assert.match(await p.locator('#portalMessage').textContent(),/并非新注册/);assert.equal(await p.locator('.billing-channel').isVisible(),false);const a=await p.locator('.billing-main').boundingBox(),b=await p.locator('.ws-status').boundingBox();assert.ok(Math.abs(a.x-b.x)<1&&Math.abs(a.width-b.width)<1);}assert.ok(await noOverflow(p));});
