// Local-only typography evidence. All API responses are fixtures; no production requests.
const fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=process.env.AUDIT_OUTPUT;
if(!out)throw Error('Set AUDIT_OUTPUT to an evidence directory');fs.mkdirSync(out,{recursive:true});
const sizes=[[1366,768],[1440,900],[1920,1080],[2560,1440],[768,1024],[390,844]];
const user={id:'local',account:'engineer',email:'engineer@example.test',display_name:'工程师测试账户',created_at:'2026-09-01T00:00:00Z',plan_name:'pro',membership:'active',expires_at:'2099-01-01T00:00:00Z',used:1200,monthly_quota:100000,task_count:12,version:'v1'};
function api(p){
 if(p.includes('/admin/operations/feedback'))return {items:[{id:'local-feedback-001',category:'translation',status:'new',created_at:'2026-09-16T00:00:00Z',email:'engineer@example.test',message:'批量翻译工程图纸时，希望保留原有标注位置，并能清楚查看处理进度。\n这是本地排版测试留言，不会发送到线上。',page:'/index.html'}],nextCursor:null};
 if(p.includes('/admin/users/'))return {user,usage:[],history:[]};
 if(p.includes('/admin/users'))return {summary:{total:1,members:1,used:1200,tasks:12},items:[user],total:1,page:1,pageSize:25,month:'2026-09',asOf:'2026-09-16'};
 const data={health:{api:'operational',database:'operational'},profile:{...user,user_id:'local'},subscription:{plan_name:'Pro',max_devices:3},usage:{used:1200,monthly_quota:100000},devices:{devices:[],max_devices:3},entitlements:{subscription:{plan_name:'pro'},usage:{used:1200,monthly_quota:100000}},plans:{paymentsEnabled:false,plans:[{id:'preview',name:'专业会员（本地展示）',duration_days:30,price_cents:9900}],message:'本地预览，不进行支付'},orders:{orders:[],nextCursor:null},glossary:{entries:[{id:'one',source:'法兰连接',target:'Flange connection',note:'工程术语示例'}],revision:1},terminology:{items:[]},history:{items:[],nextCursor:null},version:{latest_version:'2.1.1'}};return data[p.split('/').at(-1)]||{};
}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const results=[];try{
 for(const [width,height] of sizes.filter(s=>!process.env.AUDIT_WIDTH||s[0]===Number(process.env.AUDIT_WIDTH))){const ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,reducedMotion:'reduce'});
 await ctx.addInitScript(()=>window.name!=='logged-out'&&sessionStorage.setItem('dwgc2e.session',JSON.stringify({token:'LOCAL-ONLY',userId:'local',expiresAt:'2099-01-01'})));
 await ctx.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='typography.local')return route.abort();if(u.pathname==='/api/v1/admin/session')return route.fulfill({status:route.request().method()==='GET'?401:200,json:{authenticated:route.request().method()!=='GET'}});if(u.pathname.startsWith('/api/'))return route.fulfill({json:api(u.pathname)});const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep))return route.abort();return route.fulfill({status:fs.existsSync(f)?200:404,contentType:({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2'})[path.extname(f)]||'application/octet-stream',body:fs.existsSync(f)?fs.readFileSync(f):'missing'});});
 for(const file of fs.readdirSync(root).filter(f=>f.endsWith('.html'))){const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://typography.local/'+file);await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(200);
 const capture=async state=>{await p.evaluate(async()=>{const images=[...document.images];for(const img of images){img.loading='eager';}await Promise.all(images.map(img=>img.decode().catch(()=>{})));});const metrics=await p.evaluate(()=>{
 const visible=e=>!!(e.offsetWidth||e.offsetHeight||e.getClientRects().length)&&getComputedStyle(e).visibility!=='hidden';
 const texts=[...document.querySelectorAll('body *')].filter(e=>visible(e)&&!e.closest('svg')&&[...e.childNodes].some(n=>n.nodeType===3&&n.textContent.trim()));
 return {overflow:document.documentElement.scrollWidth>innerWidth+1,undersizedControls:[...document.querySelectorAll('button,a.btn,input:not([type=checkbox]):not([type=radio]),select,textarea')].filter(e=>visible(e)&&!e.closest('svg')&&parseFloat(getComputedStyle(e).fontSize)>0&&parseFloat(getComputedStyle(e).fontSize)<14).map(e=>({selector:e.tagName+'.'+e.className,px:parseFloat(getComputedStyle(e).fontSize)})),small:texts.filter(e=>parseFloat(getComputedStyle(e).fontSize)<14).map(e=>({selector:e.tagName.toLowerCase()+'.'+e.className,text:e.textContent.trim().slice(0,90),px:parseFloat(getComputedStyle(e).fontSize)})),clipped:texts.filter(e=>{if(e.classList.contains('sr-only')||!['hidden','clip'].includes(getComputedStyle(e).overflowY))return false;const b=e.getBoundingClientRect();return [...e.childNodes].filter(n=>n.nodeType===3&&n.textContent.trim()).some(n=>{const r=document.createRange();r.selectNodeContents(n);return [...r.getClientRects()].some(t=>t.bottom>b.bottom+2||t.top<b.top-2);});}).map(e=>({selector:e.tagName+'.'+e.className,text:e.textContent.trim().slice(0,60)}))};});results.push({file,state,width,height,...metrics,errors:[...errors]});const base=path.join(out,`${file.replace('.html','')}--${state}--${width}`);await p.screenshot({path:base+'--viewport.png'});await p.screenshot({path:base+'--full.png',fullPage:true});};
 await capture('default');
 if(file==='admin-feedback.html'){await p.locator('#userKey').fill('local-preview-only-'.repeat(3));await p.locator('#userLogin button').click();await p.locator('#userWorkspace:visible').waitFor();await capture('messages');}
 if(file==='admin-users.html'){await p.locator('#userKey').fill('local-preview-only-'.repeat(3));await p.locator('#userLogin button').click();await p.locator('#userWorkspace:visible').waitFor();await capture('users');await p.getByRole('button',{name:'查看详情'}).click();await p.locator('#detailContent:visible').waitFor();await capture('detail');}
 if(file==='account.html'){await p.evaluate(()=>{sessionStorage.clear();window.name='logged-out';});await p.reload();await p.waitForTimeout(200);await capture('login');}
 await p.close();}await ctx.close();}
 }finally{await browser.close();const resultFile=path.join(out,'responsive.json');const previous=process.env.AUDIT_WIDTH&&fs.existsSync(resultFile)?JSON.parse(fs.readFileSync(resultFile)).filter(r=>r.width!==Number(process.env.AUDIT_WIDTH)):[];fs.writeFileSync(resultFile,JSON.stringify([...previous,...results],null,2));}
 const failed=results.filter(r=>r.overflow||r.errors.length||r.clipped.length||r.undersizedControls.length);console.log(JSON.stringify({checks:results.length,failed,clipped:results.filter(r=>r.clipped.length).map(r=>({file:r.file,state:r.state,width:r.width,items:r.clipped}))},null,2));if(failed.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
